language: node_js
node_js:
- stable
sudo: required
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
- sed -i "s/\/master\//\/$TRAVIS_BRANCH\//g" README.md
- npm run doc
after_success:
- scripts/jsdoc/publish.sh
env:
  global:
  # GH_TOKEN is configured in travis web ui
  - CF_APP=watson-speech
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=sdks
  - CF_USERNAME=nfriedly@us.ibm.com
  - secure: NDOdoAt1bjGspsU9CZl494GW9OEC9J56OCJloyfd0KGkDmKLNpYGw5eHXmJfLVqKAvldhOpjp0aNSrrwVcT2qvE2dhtYkL+a5hVMZFr7DdfOtZze/MIdCpoQhZQz8+wQa82crGgf+cTL2Y+BndkQoDk5mMo/3sAf512euHTHJXb+9DZ36ZJYIK/hVTfzZMdUUH7059rYeUADhXXcbu1Va+cJHXr2xRFI8ZEdZfZ0V1jDEqPyi/hwDYODgsTpk/4jRFlkZu2Agxq2kOETeuJYiTJ7O9Q1qhY3rSAgu/rvQK8+Y7ngTxWS8rStOOr8CNXJtmZdM0zpz6RbmQEhR5Xk4s8aX1rxPDj06/Cx7BVWKZWb7wGJETjKq/+NLv/tK9tXDVZ5oBj/H9VkUm2gWqWCKaAge9xW+wuh/LluGMZIx+pTDI94AbgIZnxP2HoALmGIvyim7AquvQqaqIqVR3XTXZUccYM5yRCkxHknZbbL/hX4GOM/I1Ue24d5wt4okkGV2R/DNWYfnajB7GZOTvK5/kn7x6bJpU0Ls9ZYW+4V0zUO/3g5KalU3Cire/dSOC7WzrL823koEgpF9KCVjtCCsj1wMZI099FTGFljqfzlVKMy4Sw4tafRjpkQQT3GLoX1CV/B4n4BDOySoGBPlM0JYiEua+J5GNpeq34n38bwn4g=
before_deploy:
- npm run build
- npm install -g cf-blue-green
deploy:
- provider: releases
  api_key:
    secure: H5ykqiOnawQxu/tjHtEKAWy2BivWD3gZI8EljVejqQO+kJLcDqJA6qjj1cCQ6kNHoEgAW8se0F9EXGpIpDt8w0Bj7t0hpzT+F/zVvAhWFTKoheugQzkvIrZzBQH1Szg2I25O1PR+f5jwu1vpnPNiu2axU85hIF8eHiscwwHd7UuD7kyGHFEBqiGp+mSDhrwMeEGDdpiojN8uHd2YFFDRZPCqdu+Sft7Y0PmUMFpMSmqQ9pttYDf27K9jowYcT7Qh8XCjX+3p/RXQcSQM6gp4mRo9bcYhPTcZeA0S5Bo/yiDE9QfiD6+pj7u6yGJG8yDZouiVwclA0Pjaf9ntjW1aKNeqBthYfxYq0XJ9Ac3GJvwdQm2lbcsvHFrr106yNlJCHrRd3CiW34MfPn+RrjmEjPMYzGYd1qEEbyAEx/oA6g7LCi/f3ZwQPBsrr9ChhdsfyCvTDzwz5NpxuV2ybqLL4fEGMJdIuFmGUlVWKhbsBZouPFsFz5FTDdHsap+s4WErpQXmUv69zC9ueQOPyRdNzRw6mnN0n4pFXJiIWcolCiK5wUjbUITD6rfvUd4U/4jU0YAk824nivlesTWInmQSTmYvQWi6XJ+LX8XxJwGf4Vw8qJc66RKP+Y2mNyvQu2uUebT1TObY6VhMYGj2gYi+pVzc9NyD25U//8JxgIt1b2c=
  file:
  - dist/watson-speech.js
  - dist/watson-speech.min.js
  - dist/watson-speech.min.js.map
  skip_cleanup: true
  on:
    tags: true
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: BLUhAAznbnzWOsEyDDK7ZsPsCMWyNu/d4+FygvHGMe/u70skIywgJ2yuIQz3B3BJjkppBrUPfL6k8gYUw9zQ6y0lCTYmDNZgzlULrFOFny9U9YfqqtJhsHUJFCYTZqBA4GYppuMLQTToCoHXwIw21INFtXjQe6xWRGmsd8OJLNRKL2YllS+apDhj6CKR5QD5eh70dCAJyQvXqZGZXvgcRV49sGWV8NmiaBx+kp2Hc+z91937sEKaHS5AnGo8r8xyuS8ndBQ07jK75CJr7c2Mw64rGbhtbimRG+t1Lht9t6UzClNNAhjdueyTGZEspPMM25Bd0pkXtNMeOAxBmCRUgtF6P5s3Z59RKh9DitanTQLj5poF2k8LcBWHuNF6AmpgqEByFE75d54+plstLV7cja0INkAbhtexPk0KvWXHBYd9E9YF2zJEFM3HNG9roIlkSoPCdrzws6h6YO2H8FP60tTBa/2FUvGvaugypyZduZk7Kgo9qk/St2FJYgYJgMtlWvGoBsMKH88XbM1+hM8fc2kaPtJgoEKgT103/AtoChDNwIMw5nZJ/iowZ7KWXzjlcwh9GAJjETS63AmXQVLkDGnETPE52bAYJJowje6loexmH5CmN1NPRntK9sMXk5y5ISMtHdR5uBhX8dEqw2GH8EBvzF1bEbRVkybLARLvIjQ=
  on:
    tags: true
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: script
  script: cd examples/ && cf-blue-green-travis
  skip_cleanup: true
  on:
    branch: master
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: script
  script: scripts/create_semver_tag.sh
  on:
    branch: master
    repo: watson-developer-cloud/speech-javascript-sdk
